backend:
  name: github
  repo: adammunji/translator
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "المقالات"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "العنوان", name: "title", widget: "string" }
      - { label: "التاريخ", name: "date", widget: "datetime" }
      - { label: "المحتوى", name: "body", widget: "markdown" }
